try {
    console.log(a);
} catch (e) { 
    console.log("Catch done");
    console.log(e);
}